### ISSUE TITLE
Decocraft +2

### ISSUE THREAD

**Issue by andrewminer** [andrewminer/crafting-guide#206]
[Official Minecraft Forum](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292016-decocraft-2-2-decorations-for-minecraft-halloween)

**Comment by ThePsionic** [comment]
I'd pick this up, but the issue with Decocraft is that it uses a different workbench to make items, requiring certain amounts of clay to make. There are things that cost 72 clay to make divided over three colours, so unless the input can support amounts there's going to be a problem.

**Comment by andrewminer** [comment]
Inputs do support amounts, though the documentation hasn't been updated to reflect it.  When specifying the list of items with the `input` command, just add the amount before the name of the item.  Here's an example from the Mekanism mod version file:
```
    item: Basic Control Circuit
        recipe:
            input: 10 Osmium Ingot, Compressed Redstone
            pattern: ... 1.0 ...
            quantity: 10
            tools: Metallurgic Infuser
```
